use LojaTodo5;

insert into
Produtos (descricao, marca, cor, valor, tamanho, categoria)
values
( 'CAMISETA SLIM EM ALGODÃO MANGA CURTA COM ESTAMPA GEOMÉTRICA', 'REQUEST', 'BRANCO', '49.90', 'P', 'CAMISETA'),
( 'CAMISA EM LINHO MANGA LONGA LISA', 'MARFINNO', 'PRETO', '119.90', 'M', 'CAMISA'),
( 'CALÇA SKINNY EM JEANS', 'MARFINNO', 'PRETO', '119.90', 'M', 'CAMISA'),
( 'CAMISA MANGA CURTA EM ALGODÃO COM BORDADO NO PEITO', 'MARFINNO', 'AZUL', '49.90', 'M', 'CAMISA'),
( 'CAMISETA SLIM BÁSICA EM ALGODÃO MANGA CURTA', 'MARFINNO', 'BRANCO', '29.90', 'M', 'CAMISETA'),
( 'BLUSÃO HELANCA COM FECHAMENTO FRONTAL POR ZÍPER', 'BLUESTEEL', 'VERMELHO', '119.90', 'GG', 'BLUSÃO'),
( 'CALÇA JEANS SLIM BÁSICA', 'BLUESTEEL', 'AZUL', '129.90', 'PP', 'CALÇA'),
( 'CAMISA CANELADA MANGA LONGA', 'REQUEST', 'AZUL', '79.90', 'M', 'CAMISA'),
( 'CAMISA LISTRADA COM BOLSO', 'REQUEST', 'BRANCO', '59.90', 'G', 'CAMISA'),
( 'JAQUETA JEANS BÁSICA', 'BLUESTEEL', 'AZUL', '129.90', 'GG', 'JAQUETA'),
( 'CALÇA JOGGUER CAMUFLADA', 'MARFINNO', 'PRETO', '149.90', 'M', 'CALÇA'),
( 'BOMBER COM ZIPER', 'REQUEST', 'AZUL', '219.90', 'P', 'BOMBER'),
( 'CALÇA RETA LISA', 'MARFINNO', 'BRANCO', '139.90', 'G', 'CALÇA'),
( 'CAMISETA ESTAMPADA MANGA CURTA', 'REQUEST', 'VERMELHO', '49.90', 'PP', 'CAMISETA'),
( 'CAMISETA SLIM BÁSICA EM ALGODÃO MANGA CURTA', 'BLUESTEEL', 'PRETO', '39.90', 'PP', 'CAMISETA');
